#!/usr/bin/env bash

 bldr=$(which bldr)

if [ -x "$bldr" ] ; then
    $bldr build -p tdd
else
    if [ ! -f ./bldr.phar ]; then
        curl -sS http://bldr.io/installer | php
    fi

    ./bldr.phar build -p tdd
fi
